# Exercise: Coevolution in mutualistic networks

## Simulating coevolution in mutualistic networks

In the lecture, we built a coevolutionary model that describes how the mean value of a continuous trait $\overline{z}_{i}$, for a species $i$, evolves in response to the selective pressures of mutualistic interactions and other sources in the environment that favor an optimal trait value, $\theta_{i}$. This model is a simplified version of the one present in [Guimarães et al. (2017)](https://www.nature.com/articles/nature24273). 

The starting point of our model was the classic equation from quantitative genetics by Russel Lande (1976). Using this equation as a starting point, we incorporated the selective pressures of mutualistic interactions and other sources in the environment directly assuming how the selection gradient, $\frac{\partial ln\overline{W_i}}{\partial \overline{z}_i}$, depends on these two sources. We first assumed that for each species $i$, mutualistic interactions contribute with a fraction $m_{i}$ and the environment contributes with the remaining $(1-m_{i})$. Next, we assumed that the selective pressures from mutualistic partners, $m_{i}$, are distributed among all the $j$ partners of species $i$ such that each partner contributes with a fraction $q_{ij}$ to $m_{i}$ and favor trait complementarity, $(\overline{z}_j-\overline{z}_i)$. For simplicity, we set $q_{ij}=\frac{a_{ij}}{\sum_{i=1, i\neq j}^{N}a_{ij}}$, where $a_{ij}=1$ if species $i$ interacts with species $j$ and $a_{ij}=0$ otherwise. Finally, we assumed that the remaining $(1-m_{i})$ sources of selection in the environment favor complementarity with an optimal trait value, $(\theta_{i}-\overline{z}_i)$. Under these assumptions, we arrived at the following equation:

$$
\overline{z}_i^{(t+1)}=\overline{z}_i^{(t)}+h_{i}^2\sigma^2_{i}\left[m_{i}\sum_{i=1, i\neq j}^{N}q_{ij}(\overline{z}_j^{(t)}-\overline{z}_i^{(t)})+(1-m_{i})(\theta_{i}-\overline{z}_i^{(t)}) \right]
$$
where $h^2_{i}$ is the narrow-sense heritability of trait $\overline{z}_i$ and $\sigma^2_{i}$ is the phenotypic variance of trait $\overline{z}_i$, which is assumed to be normally distributed.

To simulate the coevolutionary dynamics using this equation, we will use a slightly different approach than what we have been using so far. Once more, our first step will be to define a 

Next, we need to define a data structure that will store mean trait values over time. In this case, since we will be dealing with multiple species, it is better to work with a matrix instead of a vector. This matrix will store in each column the values of $\overline{z}_i$ for each species $i$, and each row will store the values for a given generation $t$, as follows:

```{r, out.width="65%", out.height="65%"}

tmax=100 #Setting the maximum number of time steps in the simulation

n_sp=nrow(A) #Setting a number of species. It is equal to the number of rows in the matrix of interactions

dz=matrix(data=NA, nrow=tmax, ncol=n_sp)
colnames(dz)=paste0("SP", 1:n_sp)

print(dz[1:5,]) #Visualizing the first 5 rows

```
The dimensions of this matrix will depend on the number of species and maximum number of time steps of our simulation.

## Quantifying indirect evolutionary effects
